jinx: Upgrade to 0.2.1

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (C) 2022-2023, mintsuki
+# Copyright (C) 2022-2023 mintsuki
 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -25,8 +25,10 @@
 
 set -e
 
-jinx_version="0.2.0"
 jinx_major_ver="0.2"
+jinx_minor_ver="1"
+
+jinx_version="${jinx_major_ver}.${jinx_minor_ver}"
 
 IFS=" ""	"'
 '
@@ -34,8 +36,17 @@ IFS=" ""	"'
 LC_COLLATE=C
 export LC_COLLATE
 
+die() {
+    echo "$1"
+    exit 1
+}
+
+if ! [ "$(uname -s)" = "Linux" ]; then
+    die "$0: Jinx only supports running on Linux hosts."
+fi
+
 max_threads_by_mem="$(( $(free | awk '/^Mem:/{print $2}') / 1024 / 1024 ))"
-parallelism="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || psrinfo -tc 2>/dev/null || echo 1)"
+parallelism="$(nproc 2>/dev/null || echo 1)"
 parallelism="$(( $parallelism < $max_threads_by_mem ? $parallelism : $max_threads_by_mem ))"
 build_dir="$(pwd -P)"
 
@@ -69,11 +80,6 @@ fi
 
 pacman_cache="$JINX_CACHE_DIR/pacman"
 
-die() {
-    echo "$1"
-    exit 1
-}
-
 temp_collect=""
 trap 'rm -rf $temp_collect; trap - EXIT; exit' EXIT INT TERM QUIT HUP
 
@@ -106,8 +112,8 @@ get_hostdeps_file_run() {
     deps_to_do=""
 
     for hostdep in ${hostrundeps}; do
-        grep "${hostdep} " "${hostdeps_file}" >/dev/null 2>&1 || deps_to_do="${deps_to_do} ${hostdep}"
-        grep "${hostdep} " "${hostdeps_file}" >/dev/null 2>&1 || printf "${hostdep} " >> "${hostdeps_file}"
+        grep " ${hostdep} " "${hostdeps_file}" >/dev/null 2>&1 || deps_to_do="${deps_to_do} ${hostdep}"
+        grep " ${hostdep} " "${hostdeps_file}" >/dev/null 2>&1 || printf " ${hostdep} " >> "${hostdeps_file}"
     done
 
     for hostdep in ${deps_to_do}; do
@@ -119,8 +125,8 @@ get_hostdeps_file() {
     deps_to_do=""
 
     for hostdep in ${hostdeps} ${hostrundeps}; do
-        grep "${hostdep} " "${hostdeps_file}" >/dev/null 2>&1 || deps_to_do="${deps_to_do} ${hostdep}"
-        grep "${hostdep} " "${hostdeps_file}" >/dev/null 2>&1 || printf "${hostdep} " >> "${hostdeps_file}"
+        grep " ${hostdep} " "${hostdeps_file}" >/dev/null 2>&1 || deps_to_do="${deps_to_do} ${hostdep}"
+        grep " ${hostdep} " "${hostdeps_file}" >/dev/null 2>&1 || printf " ${hostdep} " >> "${hostdeps_file}"
     done
 
     for hostdep in ${deps_to_do}; do
@@ -132,8 +138,8 @@ get_builddeps_file() {
     deps_to_do=""
 
     for dep in ${deps} ${builddeps}; do
-        grep "${dep} " "${deps_file}" >/dev/null 2>&1 || deps_to_do="${deps_to_do} ${dep}"
-        grep "${dep} " "${deps_file}" >/dev/null 2>&1 || printf "${dep} " >> "${deps_file}"
+        grep " ${dep} " "${deps_file}" >/dev/null 2>&1 || deps_to_do="${deps_to_do} ${dep}"
+        grep " ${dep} " "${deps_file}" >/dev/null 2>&1 || printf " ${dep} " >> "${deps_file}"
     done
 
     for dep in ${deps_to_do}; do
@@ -145,8 +151,8 @@ get_deps_file() {
     deps_to_do=""
 
     for dep in ${deps}; do
-        grep "${dep} " "${deps_file}" >/dev/null 2>&1 || deps_to_do="${deps_to_do} ${dep}"
-        grep "${dep} " "${deps_file}" >/dev/null 2>&1 || printf "${dep} " >> "${deps_file}"
+        grep " ${dep} " "${deps_file}" >/dev/null 2>&1 || deps_to_do="${deps_to_do} ${dep}"
+        grep " ${dep} " "${deps_file}" >/dev/null 2>&1 || printf " ${dep} " >> "${deps_file}"
     done
 
     for dep in ${deps_to_do}; do
@@ -200,39 +206,45 @@ prepare_container() {
     make_temp -d
     sysroot_dir="${tmp}"
 
-    for hostdep in $(cat "${hostdeps_file}"); do
-        cp -Plrf "${build_dir}"/host-pkgs/${hostdep}/usr/local/. "${container_pkgs}"/
-    done
-
     for dep in $(cat "${deps_file}"); do
         cp -Plrf "${build_dir}"/pkgs/${dep}/. "${sysroot_dir}"/
     done
 
-    imagedeps="$(echo "${imagedeps}" | xargs -n1 | sort -u | xargs)"
+    native_mode="$(. "$JINX_CONFIG_FILE_PATH" && echo "$JINX_NATIVE_MODE")"
 
-    pkgset=""
-    for pkg in ${imagedeps}; do
-        pkgset="${pkgset}${pkg}/"
-
-        if [ -d "$JINX_CACHE_DIR/sets/${pkgset}.image" ]; then
-            continue
-        fi
-
-        mkdir -p "$JINX_CACHE_DIR/sets/${pkgset}"
-
-        cp -Plrf "$JINX_CACHE_DIR/sets/${pkgset}../.image" "$JINX_CACHE_DIR/sets/${pkgset}.image"
-
-        if ! run_in_container1 "$JINX_CACHE_DIR/sets/${pkgset}.image" pacman --needed --noconfirm -S "${pkg}"; then
-            die 'Jinx error: Installing an imagedep failed. If the error is not due to a non-existant package, try running `jinx rebuild-cache` and try again.'
-        fi
-
-        # Fix permissions of files
-        for f in $(find "$JINX_CACHE_DIR/sets/${pkgset}.image" -perm 000 2>/dev/null); do
-            chmod 755 "$f"
+    if [ "$native_mode" = "yes" ] && [ -z "$cross_compile" ]; then
+        imgroot="${sysroot_dir}"
+    else
+        for hostdep in $(cat "${hostdeps_file}"); do
+            cp -Plrf "${build_dir}"/host-pkgs/${hostdep}/usr/local/. "${container_pkgs}"/
         done
-    done
 
-    imgroot="$JINX_CACHE_DIR/sets/${pkgset}.image"
+        imagedeps="$(echo "${imagedeps}" | xargs -n1 | sort -u | xargs)"
+
+        pkgset=""
+        for pkg in ${imagedeps}; do
+            pkgset="${pkgset}${pkg}/"
+
+            if [ -d "$JINX_CACHE_DIR/sets/${pkgset}.image" ]; then
+                continue
+            fi
+
+            mkdir -p "$JINX_CACHE_DIR/sets/${pkgset}"
+
+            cp -Plrf "$JINX_CACHE_DIR/sets/${pkgset}../.image" "$JINX_CACHE_DIR/sets/${pkgset}.image"
+
+            if ! run_in_container1 "$JINX_CACHE_DIR/sets/${pkgset}.image" pacman --needed --noconfirm -S "${pkg}"; then
+                die 'Jinx error: Installing an imagedep failed. If the error is not due to a non-existant package, try running `jinx rebuild-cache` and try again.'
+            fi
+
+            # Fix permissions of files
+            for f in $(find "$JINX_CACHE_DIR/sets/${pkgset}.image" -perm 000 2>/dev/null); do
+                chmod 755 "$f"
+            done
+        done
+
+        imgroot="$JINX_CACHE_DIR/sets/${pkgset}.image"
+    fi
 }
 
 run_in_container() {
@@ -250,6 +262,22 @@ run_in_container() {
         run_in_cont_colorterm="--env COLORTERM=\"$COLORTERM\""
     fi
 
+    touch "${imgroot}/jinx"
+    chmod +x "${imgroot}/jinx"
+    mkdir -p "${imgroot}/base_dir" "${imgroot}/sources" "${imgroot}/build_dir"
+
+    native_mode="$(. "$JINX_CONFIG_FILE_PATH" && echo "$JINX_NATIVE_MODE")"
+
+    native_mode_mounts=""
+    if ( [ "$native_mode" = "yes" ] && [ "$cross_compile" = "yes" ] ) || ( ! [ "$native_mode" = "yes" ] ); then
+        mkdir -p "${imgroot}/sysroot"
+
+        native_mode_mounts=" \
+            --mount "${container_pkgs}":/usr/local:ro \
+            --mount "${sysroot_dir}":/sysroot:ro \
+        "
+    fi
+
     "$JINX_CACHE_DIR/rbrt" \
         --root "${imgroot}" \
         --uid $(id -u) \
@@ -262,16 +290,17 @@ run_in_container() {
         ${run_in_cont_colorterm} \
         --env JINX_CONFIG_FILE="$JINX_CONFIG_FILE" \
         --env JINX_SOURCE_DIR=/base_dir \
-        --mount "${container_pkgs}":/usr/local:ro \
-        --mount "${sysroot_dir}":/sysroot:ro \
+        ${native_mode_mounts} \
         --mount "${script}":/jinx:ro \
         --mount "${base_dir}":/base_dir${container_base_dir_ro} \
         --mount "${base_dir}"/sources:/base_dir/sources${container_sources_ro} \
         --mount "${build_dir}":/build_dir \
         ${unshare_net_flag} \
-        --workdir /build_dir \
+        --workdir / \
         -- \
-        /jinx "$@"
+        /bin/sh -c "cd /build_dir && /jinx $*"
+
+    rm -rf "${imgroot}/sysroot" "${imgroot}/jinx" "${imgroot}/base_dir" "${imgroot}/sources" "${imgroot}/build_dir"
 }
 
 destroy_container() {
@@ -526,6 +555,7 @@ do_package() {
 precont_patch() {
     [ -f "${base_dir}"/sources/$1.patched ] && return
 
+    cross_compile=yes
     prepare_container
     run_in_container internal-cont-patch $1
     destroy_container
@@ -540,6 +570,7 @@ do_source() {
 
     "${script}" internal-precont-patch $1
 
+    cross_compile=yes
     prepare_container
     run_in_container internal-regenerate $1
     destroy_container
@@ -591,6 +622,7 @@ do_cmd_regenerate() {
 
     rm -rf "${base_dir}"/sources/$1.regenerated
 
+    cross_compile=yes
     prepare_container
     run_in_container internal-regenerate $1
     destroy_container
@@ -607,6 +639,7 @@ do_host_pkg() {
     [ -f "${base_dir}"/sources/${from_source}.regenerated ] || \
         "${script}" internal-source "${from_source}"
 
+    cross_compile=yes
     prepare_container
 
     container_sources_ro=":ro"
@@ -1136,11 +1169,6 @@ reinit_container() {
     echo 'Server = https://mirror.netcologne.de/archlinux/$repo/os/$arch' >> "$JINX_CACHE_DIR/sets/.image/etc/pacman.d/mirrorlist"
     echo 'en_US.UTF-8 UTF-8' > "$JINX_CACHE_DIR/sets/.image/etc/locale.gen"
     mkdir "$JINX_CACHE_DIR/sets/.image/etc/pacman.d/gnupg"
-    mkdir "$JINX_CACHE_DIR/sets/.image/sysroot"
-    mkdir "$JINX_CACHE_DIR/sets/.image/base_dir"
-    mkdir "$JINX_CACHE_DIR/sets/.image/build_dir"
-    touch "$JINX_CACHE_DIR/sets/.image/jinx"
-    chmod +x "$JINX_CACHE_DIR/sets/.image/jinx"
     run_in_container1 "$JINX_CACHE_DIR/sets/.image" locale-gen
     run_in_container1 "$JINX_CACHE_DIR/sets/.image" pacman-key --init
     run_in_container1 "$JINX_CACHE_DIR/sets/.image" pacman-key --populate archlinux
