ports: misc backport of recipes

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -26,7 +26,7 @@
 set -e
 
 jinx_major_ver="0.2"
-jinx_minor_ver="13"
+jinx_minor_ver="15"
 
 jinx_version="${jinx_major_ver}.${jinx_minor_ver}"
 
@@ -46,12 +46,13 @@ if ! [ "$(uname -s)" = "Linux" ]; then
 fi
 
 if [ -z "$JINX_PARALLELISM" ]; then
-    max_threads_by_mem="$(( $(free | awk '/^Mem:/{print $2}') / 1024 / 1024 / 2 ))"
+    max_threads_by_mem="$(( ((($(free | awk '/^Mem:/{print $2}') + 1048575) / 1048576) + 1) / 2 ))"
     parallelism="$(nproc 2>/dev/null || echo 1)"
     parallelism="$(( $parallelism < $max_threads_by_mem ? $parallelism : $max_threads_by_mem ))"
 else
     parallelism="$JINX_PARALLELISM"
 fi
+
 build_dir="$(pwd -P)"
 
 if [ -z "$JINX_SOURCE_DIR" ]; then
@@ -467,8 +468,25 @@ default_recipe_steps() {
     }
 }
 
+source_source_recipe() {
+    if [ -f "${base_dir}"/source-recipes/$1 ]; then
+        . "${base_dir}"/source-recipes/$1
+    elif [ -f "${base_dir}"/recipes/$1 ]; then
+        . "${base_dir}"/recipes/$1
+
+        unset deps
+        unset builddeps
+        unset hostrundeps
+        imagedeps="${source_imagedeps}"
+        hostdeps="${source_hostdeps}"
+        allow_network="${source_allow_network}"
+    else
+        die "* could not find source recipe '$1'"
+    fi
+}
+
 cont_patch() {
-    . "${base_dir}"/source-recipes/$1
+    source_source_recipe $1
 
     get_real_source_dir
 
@@ -501,7 +519,7 @@ cont_patch() {
 do_regenerate() {
     default_recipe_steps
 
-    . "${base_dir}"/source-recipes/$1
+    source_source_recipe $1
 
     get_real_source_dir
 
@@ -527,9 +545,9 @@ do_build_host() {
     mkdir -p "${build_dir}"/host-builds/${name}
 
     if ! [ -z "${from_source}" ]; then
-        version=$(. "${base_dir}"/source-recipes/${from_source} && echo "$version")
+        version=$(unset version && source_source_recipe ${from_source} && echo "$version")
+        source_dir="$(unset source_dir && source_source_recipe ${from_source} && echo "$source_dir")"
 
-        source_dir="$(. "${base_dir}"/source-recipes/${from_source} && echo "$source_dir")"
         if [ -z "${source_dir}" ]; then
             source_dir="${base_dir}"/sources/${from_source}
         else
@@ -561,9 +579,9 @@ do_package_host() {
     mkdir -p "${dest_dir}"
 
     if ! [ -z "${from_source}" ]; then
-        version=$(. "${base_dir}"/source-recipes/${from_source} && echo "$version")
+        version=$(unset version && source_source_recipe ${from_source} && echo "$version")
+        source_dir="$(unset source_dir && source_source_recipe ${from_source} && echo "$source_dir")"
 
-        source_dir="$(. "${base_dir}"/source-recipes/${from_source} && echo "$source_dir")"
         if [ -z "${source_dir}" ]; then
             source_dir="${base_dir}"/sources/${from_source}
         else
@@ -598,10 +616,14 @@ do_build() {
 
     mkdir -p "${build_dir}"/builds/${name}
 
-    if ! [ -z "${from_source}" ]; then
-        version=$(. "${base_dir}"/source-recipes/${from_source} && echo "$version")
+    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${source_dir}" ]; then
+        if ! [ -z "${from_source}" ]; then
+            version=$(unset version && source_source_recipe ${from_source} && echo "$version")
+            source_dir="$(unset source_dir && source_source_recipe ${from_source} && echo "$source_dir")"
+        else
+            from_source=${name}
+        fi
 
-        source_dir="$(. "${base_dir}"/source-recipes/${from_source} && echo "$source_dir")"
         if [ -z "${source_dir}" ]; then
             source_dir="${base_dir}"/sources/${from_source}
         else
@@ -632,10 +654,14 @@ do_package() {
     rm -rf "${dest_dir}"
     mkdir -p "${dest_dir}"
 
-    if ! [ -z "${from_source}" ]; then
-        version=$(. "${base_dir}"/source-recipes/${from_source} && echo "$version")
+    if ! [ -z "${from_source}" ] || ! [ -z "${tarball_url}" ] || ! [ -z "${source_dir}" ]; then
+        if ! [ -z "${from_source}" ]; then
+            version=$(unset version && source_source_recipe ${from_source} && echo "$version")
+            source_dir="$(unset source_dir && source_source_recipe ${from_source} && echo "$source_dir")"
+        else
+            from_source=${name}
+        fi
 
-        source_dir="$(. "${base_dir}"/source-recipes/${from_source} && echo "$source_dir")"
         if [ -z "${source_dir}" ]; then
             source_dir="${base_dir}"/sources/${from_source}
         else
@@ -670,7 +696,7 @@ precont_patch() {
 }
 
 do_source() {
-    . "${base_dir}"/source-recipes/$1
+    source_source_recipe $1
 
     get_real_source_dir
 
@@ -703,7 +729,7 @@ do_cmd_host_rebuild() {
 }
 
 do_cmd_regenerate() {
-    . "${base_dir}"/source-recipes/$1
+    source_source_recipe $1
 
     [ -f "${base_dir}"/sources/$1.patched ] || die "cannot regenerate non-built package"
 
@@ -773,6 +799,10 @@ do_pkg() {
         from_source="$(. "${base_dir}"/recipes/$1 && echo "$from_source")"
         [ -f "${base_dir}"/sources/${from_source}.regenerated ] || \
             "${script}" internal-source "${from_source}"
+    fi
+
+    if ! [ -z "${tarball_url}" ] || ! [ -z "${source_dir}" ]; then
+        "${script}" internal-source "${name}"
     fi
 
     prepare_container
